### PR TITLE
This change removes the deprecation warning received whilst compiling Android

### PR DESCRIPTION
**Pull request by rodrigoelp**
Basically, stopped using view.loop(true or false) to use view.setRepeatCount(INFINITE or 0)
which, can be extended in the future (removing loop for setRepeatCount directly)

### CODE REVIEW

**Comment by rodrigoelp** [comment]
Hi @emilioicai, this PR should remove the deprecation warning commented here: #392

I will test it more later, unfortunately my Android environment here is giving me lots of issues and I was not able to properly test this code.

Let me know if you have comments to address it promptly.

**Comment by emilioicai** [comment]
Looks good to me. I will give it a try and wait for you to test before merging. Let me know how it went.

**Comment by rodrigoelp** [comment]
Hi @emilioicai, I've done my testing. It seems to work fine on different Android API's. I am happy to merge this if you are happy with it.

**Comment by rodrigoelp** [comment]
Woohoo!

**Pull request merged**
