### PR TITLE
Cleanup framework / header search paths to fix xcode 10 build

### PR DESCRIPTION
**Pull request by janicduplessis**
When the project is linked by including the xcodeproj (not cocoapods) there is a build error in xcode 10.

```
/Users/janic/Developer/th3rdwave/app/node_modules/react-native/ReactCommon/fabric/graphics/platform/android/Float.h:8:10: 'limits' file not found
/Users/janic/Library/Developer/Xcode/DerivedData/th3rdwave-bpfvmasmymsqitghoxzryohjjlfr/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:8:9: While building module 'UIKit' imported from /Users/janic/Library/Developer/Xcode/DerivedData/th3rdwave-bpfvmasmymsqitghoxzryohjjlfr/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
/<module-includes>:1:9: In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:21:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:21:
```

Removing those extra header and framework search paths fixes it.

### CODE REVIEW

**Comment by mysport12** [comment]
This PR fixed the issues we were having with Xcode 10 builds as well.

**Comment by janicduplessis** [comment]
Oh it's xcode 10 haha

**Comment by rodrigoelp** [comment]
Small comment to this PR, it would be great to remove the `iPhone_deployment_target` to just inherit the one configured in the project... Specially since 7.0 is no longer supported by react native 0.57.x (although that comment should apply to any dependency in an iOS project)

**Comment by janicduplessis** [comment]
@rodrigoelp Would you like to open a PR to do that since it's not too related to the fix in this PR?

**Comment by rodrigoelp** [comment]
Fair enough, I will wait until this fix gets in (hopefully very soon) and I will make that comment again (or create the PR).

The reason why I mentioned is that I always find myself writing a post install script to remove the deployment target of the libraries as it is not contributing to anything most of the time.

**Comment by emilioicai** [comment]
@rodrigoelp merged :) I'm waiting for your PR...

**Pull request merged**
